on: 
  - pull_request
  - workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-10.15

    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project node modules
        run: npm install
      - name: Install Pod dependencies
        run: cd ios && pod install
      - name: Build app
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: ./ios/reactnativebuildexercise.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          certificate-password: ${{ secrets.P12_PWD }}
          mobileprovision-base64: ${{ secrets.PROV_PROFILE_B64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          export-method: enterprise
          configuration: Release
          workspace-path: ./ios/reactnativebuildexercise.xcworkspace
          output-path: ./ios/build/reactnativebuildexercise.ipa

