on: 
  - pull_request
  - workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-10.15

    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project node modules
        run: npm install
      - name: Install Pod dependencies
        run: cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace reactnativebuildexercise.xcworkspace -scheme reactnativebuildexercise archive -archivePath reactnativebuildexercise.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./reactnativebuildexercise.xcarchive -exportPath . -exportOptionsPlist reactnativebuildexercise/Info.plist
          mv reactnativebuildexercise.ipa ../reactnativebuildexercise.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: reactnativebuildexercise.ipa
          path: ios/build/

