on: 
  - pull_request
  - workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-10.15

    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project node modules
        run: npm install
      - name: Install Pod dependencies
        run: cd ios && pod Install
      - name: Build app
        run: echo Hello

