on: 
  - pull_request
  - workflow_dispatch

jobs:
  build-ios:
    runs-on: macos-10.15

    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project node modules
        run: npm install
      - name: Install Pod dependencies
        run: cd ios && pod install
      - name: Build app
        run: |       
          xcodebuild -workspace myapp.xcworkspace -scheme myapp archive -archivePath myapp.xcarchive -allowProvisioningUpdates
          xcodebuild -exportArchive -archivePath ./myapp.xcarchive -exportPath . -exportOptionsPlist myapp/Info.plist
          mv myapp.ipa ../myapp.ipa
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: myapp.ipa
          path: ios/build/

