on: 
  - pull_request
  - workflow_dispatch

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install project node modules
        run: npm install
      - name: Get keystore from secrets
        id: write_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Set env ANDROID_KEYSTORE_PATH
        run: echo "ANDROID_KEYSTORE_PATH=${{ steps.write_file.outputs.filePath }}" >> $GITHUB_ENV
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew
        # Build Command
      - name: Build Android Release
        run: |
          cd android && ./gradlew bundleRelease
        env:
          ANDROID_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        # Upload to Artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/